#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 24 13:29:44 2021

@author: mntalha
"""


import unittest

def summ(a,b):
    return a+b
class TestClass(unittest.TestCase):
    #function name's must starts with "test"
    def test_funct1(self):
        print("HEYY")
    def test_summ(self):
        #arrange 
        a = 10
        b = 20
        #act
        #burada fonksiyon cagırılır
        result = summ(a,b)
        #assert
        self.assertEqual(result, 10)
    

if __name__ == "__main__":
    unittest.main()
    
